import { type RouteConfig, index, layout, route } from '@react-router/dev/routes';

export default [
  route('login', 'routes/login.tsx'),
  route('logout', 'routes/logout.tsx'),
  route('materials/:id/download', 'routes/materials.$id.download.tsx'),
  route('materials/:id/view', 'routes/materials.$id.view.tsx'),
  route('attendance', 'routes/attendance.tsx'),
  route('event-materials', 'routes/event-materials.tsx'),
  // Printable test document — outside the _app layout on purpose: no app shell, no nav chrome.
  route('tests/:id/print', 'routes/tests.$id.print.tsx'),
  route('enrich-vocab', 'routes/enrich-vocab.tsx'),
  route('generate-vocab', 'routes/generate-vocab.tsx'),

  // ---- JSON API (mobile app; see docs/api.md) ----
  // Resource routes only: none of these has a default export, and none is inside the
  // _app layout — they must not inherit the app-shell loader or its cookie redirect.
  route('api/auth/login', 'routes/api.auth.login.tsx'),
  route('api/auth/logout', 'routes/api.auth.logout.tsx'),
  route('api/auth/me', 'routes/api.auth.me.tsx'),
  route('api/auth/redeem-invite', 'routes/api.auth.redeem-invite.tsx'),
  route('api/auth/request-reset', 'routes/api.auth.request-reset.tsx'),
  route('api/auth/change-password', 'routes/api.auth.change-password.tsx'),
  route('api/bootstrap', 'routes/api.bootstrap.tsx'),
  route('api/dashboard', 'routes/api.dashboard.tsx'),
  route('api/events/:id?', 'routes/api.events.tsx'),
  route('api/classes/:id?', 'routes/api.classes.tsx'),
  route('api/students/:id?', 'routes/api.students.tsx'),
  route('api/staff/:id?', 'routes/api.staff.tsx'),
  route('api/parents/:id?', 'routes/api.parents.tsx'),
  route('api/invites/:id?', 'routes/api.invites.tsx'),
  route('api/materials/:id?', 'routes/api.materials.tsx'),
  route('api/assessments/scores/:id?', 'routes/api.assessments.scores.tsx'),
  route('api/assessments/behavior/:id?', 'routes/api.assessments.behavior.tsx'),
  route('api/assessment-types/reorder', 'routes/api.assessment-types.reorder.tsx'),
  route('api/assessment-types/:id?', 'routes/api.assessment-types.tsx'),
  route('api/grade-levels/reorder', 'routes/api.grade-levels.reorder.tsx'),
  route('api/grade-levels/:id?', 'routes/api.grade-levels.tsx'),
  route('api/attendance', 'routes/api.attendance.tsx'),
  route('api/event-materials', 'routes/api.event-materials.tsx'),
  route('api/flashcards/topics/:id?', 'routes/api.flashcards.topics.tsx'),
  route('api/flashcards/topic/:slug', 'routes/api.flashcards.topics.$slug.tsx'),
  route('api/flashcards/words/:id?', 'routes/api.flashcards.words.tsx'),
  route('api/flashcards/import', 'routes/api.flashcards.import.tsx'),
  // Not under `topics/`: that route's `:id?` would swallow a literal `generate-topic` segment.
  route('api/flashcards/generate-topic', 'routes/api.flashcards.generate-topic.tsx'),
  route('api/flashcards/results', 'routes/api.flashcards.results.tsx'),
  route('api/flashcards/stats', 'routes/api.flashcards.stats.tsx'),
  route('api/feedback/:id?', 'routes/api.feedback.tsx'),
  route('api/profile', 'routes/api.profile.tsx'),
  route('api/settings/theme', 'routes/api.settings.theme.tsx'),
  route('api/settings/ui-prefs', 'routes/api.settings.ui-prefs.tsx'),
  route('api/settings/notifications', 'routes/api.settings.notifications.tsx'),
  route('api/push/register', 'routes/api.push.register.tsx'),
  route('api/push/unregister', 'routes/api.push.unregister.tsx'),
  route('api/push/run', 'routes/api.push.run.tsx'),

  // The vocabulary pages used to live at /flashcards. Keep the old URLs working — bookmarks,
  // and push notifications sent before the rename that still carry `url: '/flashcards'`.
  // Outside the `_app` layout: a redirect has no business loading the app shell.
  route('flashcards', 'routes/flashcards.legacy.tsx'),
  route('flashcards/:slug', 'routes/flashcards.legacy.$slug.tsx'),

  layout('routes/_app.tsx', [
    index('routes/home.tsx'),
    route('dashboard', 'routes/dashboard.tsx'),
    route('calendar', 'routes/calendar.tsx'),
    route('classes', 'routes/classes.tsx'),
    route('people', 'routes/people.tsx'),
    route('materials', 'routes/materials.tsx'),
    route('tests', 'routes/tests.tsx'),
    route('tests/:id', 'routes/tests.$id.tsx'),
    route('my-tests', 'routes/my-tests.tsx'),
    route('my-tests/:id', 'routes/my-tests.$id.tsx'),
    route('questions', 'routes/questions.tsx'),
    route('assessments', 'routes/assessments.tsx'),
    route('vocabulary', 'routes/flashcards.tsx'),
    route('vocabulary/:slug', 'routes/flashcards.$slug.tsx'),
    route('config', 'routes/config.tsx'),
    route('feedback', 'routes/feedback.tsx'),
    route('profile', 'routes/profile.tsx'),
  ]),
] satisfies RouteConfig;
