import type { LoaderFunctionArgs } from 'react-router';
import { LogoLibraryScreen } from '../../src/logos/logo-library.jsx';
import { createRawDb } from '../../server/db/internal';
import { cloudflareCtx } from '../../app/load-context';
import { requireAdmin } from '../../server/services/auth';
import { listLogos } from '../../server/services/logos';

/**
 * /logo-library — the mascot artwork catalogue, by category and subject.
 *
 * `requireAdmin`, not `requireStaff`, for the same reason as /garden-species: this is a catalogue
 * of shared reference art for whoever runs the school, not a view of anyone's class. The nav row
 * is `adminOnly` too, but the guard is what enforces it — a hidden link is not a permission.
 *
 * The raw db handle rather than `tenantDbFor`: logo_library has no tenant_id on purpose (see
 * migrations/0056_logo_library.sql). This is the one screen where that is correct.
 *
 * Filter and page live in the URL, not in component state, so a filtered view is linkable and the
 * back button steps through it. It also keeps the loader honest: the library is ~3.4k rows and one
 * page is 120, so the payload stays small no matter how big the corpus grows.
 *
 * Read-only by design — there is no action here. Rows are generated by scripts/import-logos.mjs and
 * applied as a seed; a catalogue you can also edit is a catalogue that drifts from its source.
 */
export async function loader({ request, context }: LoaderFunctionArgs) {
  const env = context.get(cloudflareCtx).env;
  await requireAdmin(request, env);

  const url = new URL(request.url);
  const page = await listLogos(createRawDb(env), {
    category: url.searchParams.get('cat'),
    q: url.searchParams.get('q'),
    page: Number(url.searchParams.get('page') ?? '1') || 1,
  });

  return page;
}

export default function LogoLibraryRoute() {
  return <LogoLibraryScreen />;
}
