// Generate scripts/logo-library-seed.sql from the ipaslogo corpus.
//
//   node scripts/import-logos.mjs --bundle <index-*.js> --logos <dir> [--out <file>]
//
// --bundle is the site's JS bundle (it carries the authoritative logo manifest: every storage key
// plus its background colour and source dimensions). --logos is the directory of downloaded .webp
// files, used only to assert that every row we emit actually has an asset behind it.
//
// Classification is the hand-authored lexicon in ./logo-taxonomy.mjs -- deterministic, no model
// call -- so re-running this against the same corpus produces byte-identical SQL.

import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { BUCKETS, parseKey, classify } from './logo-taxonomy.mjs';

function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  if (i === -1) return fallback;
  const v = process.argv[i + 1];
  if (!v || v.startsWith('--')) throw new Error(`--${name} needs a value`);
  return v;
}

const bundlePath = arg('bundle');
const logosDir = arg('logos');
const outPath = arg('out', 'scripts/logo-library-seed.sql');
if (!bundlePath || !logosDir) {
  console.error(
    'usage: node scripts/import-logos.mjs --bundle <index-*.js> --logos <dir> [--out <file>]',
  );
  process.exit(2);
}

// The bundle inlines one manifest entry per logo. Anything it does not list cannot be rendered by
// the site either (its card component throws on a missing entry), so this is the complete corpus.
const bundle = readFileSync(bundlePath, 'utf8');
const ENTRY =
  /"(logos\/[^"]+\.png)":\{backgroundColor:`(#[0-9a-fA-F]{3,8})`,width:(\d+),height:(\d+)\}/g;

const rows = [];
const seenId = new Set();
const seenKey = new Set();
let match;
while ((match = ENTRY.exec(bundle)) !== null) {
  const [, path, backgroundColor, width, height] = match;
  const file = path.replace(/^logos\//, '');
  const { hash, slug, variant } = parseKey(file);
  const { level1, level2 } = classify(slug);

  const storageKey = `logos/${file.replace(/\.png$/, '.webp')}`;
  if (seenId.has(hash)) throw new Error(`Duplicate logo id ${hash} (${slug})`);
  if (seenKey.has(storageKey)) throw new Error(`Duplicate storage key ${storageKey}`);
  seenId.add(hash);
  seenKey.add(storageKey);

  if (!BUCKETS.includes(level1)) throw new Error(`Unknown bucket "${level1}" for ${slug}`);

  rows.push({
    id: hash,
    storageKey,
    slug,
    category: level1,
    subject: level2,
    variant,
    backgroundColor,
    sourceWidth: Number(width),
    sourceHeight: Number(height),
  });
}

if (rows.length === 0) throw new Error(`No logo entries found in ${bundlePath}`);

// Every row must have bytes behind it, or the library renders broken tiles.
const onDisk = new Set(readdirSync(logosDir).filter((f) => f.endsWith('.webp')));
const missing = rows.filter((r) => !onDisk.has(r.storageKey.replace(/^logos\//, '')));
if (missing.length) {
  throw new Error(
    `${missing.length} logo(s) have no downloaded asset, e.g. ${missing[0].storageKey}. ` +
      `Re-run the download before importing.`,
  );
}

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const values = rows
  .map(
    (r) =>
      `  (${q(r.id)},${q(r.storageKey)},${q(r.slug)},${q(r.category)},${q(r.subject)},` +
      `${r.variant},${q(r.backgroundColor)},${r.sourceWidth},${r.sourceHeight})`,
  )
  .join(',\n');

// One statement per 500 rows: D1 rejects very large single statements, and a chunked file still
// applies in a single `wrangler d1 execute --file` run.
const CHUNK = 500;
const chunks = [];
for (let i = 0; i < rows.length; i += CHUNK) {
  chunks.push(
    values
      .split(',\n')
      .slice(i, i + CHUNK)
      .join(',\n'),
  );
}

const byCategory = new Map();
for (const r of rows) byCategory.set(r.category, (byCategory.get(r.category) ?? 0) + 1);
const summary = BUCKETS.map(
  (b) => `--   ${b.padEnd(18)} ${String(byCategory.get(b) ?? 0).padStart(5)}`,
).join('\n');

const sql = `-- GENERATED by scripts/import-logos.mjs -- do not edit by hand.
--
-- ${rows.length} mascot logos from ipaslogo.com ("free to download and use commercially"),
-- classified by the hand-authored lexicon in scripts/logo-taxonomy.mjs.
--
-- Apply with:  npm run db:seed:logos        (remote)
--              npm run db:seed:logos:local  (local)
--
-- Level-1 distribution:
${summary}
--   ${'distinct subjects'.padEnd(18)} ${String(new Set(rows.map((r) => r.subject)).size).padStart(5)}

DELETE FROM logo_library;

${chunks
  .map(
    (c) =>
      `INSERT INTO logo_library
  (id, storage_key, slug, category, subject, variant, background_color, source_width, source_height)
VALUES
${c};`,
  )
  .join('\n\n')}
`;

writeFileSync(outPath, sql, 'utf8');

console.log(`wrote ${outPath}`);
console.log(`  rows              ${rows.length}`);
console.log(`  distinct subjects ${new Set(rows.map((r) => r.subject)).size}`);
for (const b of BUCKETS) console.log(`  ${b.padEnd(18)} ${byCategory.get(b) ?? 0}`);
if (!existsSync(join(logosDir, rows[0].storageKey.replace(/^logos\//, '')))) {
  throw new Error('sanity check failed: first asset not readable');
}
